"""phase_5_activities_bunks_families

Revision ID: 13ee715b1156
Revises: 63a11145f50e
Create Date: 2026-02-08 21:20:27.780118

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13ee715b1156'
down_revision: Union[str, None] = '63a11145f50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('staff_required', sa.Integer(), nullable=False),
    sa.Column('equipment_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_organization_id'), 'families', ['organization_id'], unique=False)
    op.create_table('bunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('gender_restriction', sa.String(length=20), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('counselor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counselor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bunks_counselor_user_id'), 'bunks', ['counselor_user_id'], unique=False)
    op.create_index(op.f('ix_bunks_organization_id'), 'bunks', ['organization_id'], unique=False)
    op.create_table('bunk_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bunk_id', sa.UUID(), nullable=False),
    sa.Column('camper_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bunk_id'], ['bunks.id'], ),
    sa.ForeignKeyConstraint(['camper_id'], ['campers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camper_id', 'event_id', name='uq_bunk_assignment_camper_event')
    )
    op.create_index(op.f('ix_bunk_assignments_bunk_id'), 'bunk_assignments', ['bunk_id'], unique=False)
    op.create_index(op.f('ix_bunk_assignments_camper_id'), 'bunk_assignments', ['camper_id'], unique=False)
    op.create_index(op.f('ix_bunk_assignments_event_id'), 'bunk_assignments', ['event_id'], unique=False)
    op.add_column('campers', sa.Column('family_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campers_family_id'), 'campers', ['family_id'], unique=False)
    op.create_foreign_key(None, 'campers', 'families', ['family_id'], ['id'])
    op.add_column('contacts', sa.Column('family_id', sa.UUID(), nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contacts_family_id'), 'contacts', ['family_id'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contacts', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_family_id'), table_name='contacts')
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'family_id')
    op.drop_constraint(None, 'campers', type_='foreignkey')
    op.drop_index(op.f('ix_campers_family_id'), table_name='campers')
    op.drop_column('campers', 'family_id')
    op.drop_index(op.f('ix_bunk_assignments_event_id'), table_name='bunk_assignments')
    op.drop_index(op.f('ix_bunk_assignments_camper_id'), table_name='bunk_assignments')
    op.drop_index(op.f('ix_bunk_assignments_bunk_id'), table_name='bunk_assignments')
    op.drop_table('bunk_assignments')
    op.drop_index(op.f('ix_bunks_organization_id'), table_name='bunks')
    op.drop_index(op.f('ix_bunks_counselor_user_id'), table_name='bunks')
    op.drop_table('bunks')
    op.drop_index(op.f('ix_families_organization_id'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
