"""phase_4_staff_onboarding_and_rekognition

Revision ID: 63a11145f50e
Revises: a76697c99a66
Create Date: 2026-02-08 20:39:56.758231

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a11145f50e'
down_revision: Union[str, None] = 'a76697c99a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_onboardings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('personal_info_completed', sa.Boolean(), nullable=False),
    sa.Column('emergency_contacts_completed', sa.Boolean(), nullable=False),
    sa.Column('certifications_completed', sa.Boolean(), nullable=False),
    sa.Column('policy_acknowledgments_completed', sa.Boolean(), nullable=False),
    sa.Column('payroll_info_completed', sa.Boolean(), nullable=False),
    sa.Column('emergency_contacts_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_onboardings_organization_id'), 'staff_onboardings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_staff_onboardings_user_id'), 'staff_onboardings', ['user_id'], unique=True)
    op.create_table('photo_face_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('camper_id', sa.UUID(), nullable=True),
    sa.Column('face_id', sa.String(length=255), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camper_id'], ['campers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_face_tags_camper_id'), 'photo_face_tags', ['camper_id'], unique=False)
    op.create_index(op.f('ix_photo_face_tags_organization_id'), 'photo_face_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_photo_face_tags_photo_id'), 'photo_face_tags', ['photo_id'], unique=False)
    op.create_table('policy_acknowledgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['staff_onboardings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgments_onboarding_id'), 'policy_acknowledgments', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgments_organization_id'), 'policy_acknowledgments', ['organization_id'], unique=False)
    op.create_table('staff_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['staff_onboardings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_certifications_onboarding_id'), 'staff_certifications', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_staff_certifications_organization_id'), 'staff_certifications', ['organization_id'], unique=False)
    op.create_table('staff_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['staff_onboardings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_documents_onboarding_id'), 'staff_documents', ['onboarding_id'], unique=False)
    op.create_index(op.f('ix_staff_documents_organization_id'), 'staff_documents', ['organization_id'], unique=False)
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('onboarding_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_status')
    op.drop_column('users', 'department')
    op.drop_index(op.f('ix_staff_documents_organization_id'), table_name='staff_documents')
    op.drop_index(op.f('ix_staff_documents_onboarding_id'), table_name='staff_documents')
    op.drop_table('staff_documents')
    op.drop_index(op.f('ix_staff_certifications_organization_id'), table_name='staff_certifications')
    op.drop_index(op.f('ix_staff_certifications_onboarding_id'), table_name='staff_certifications')
    op.drop_table('staff_certifications')
    op.drop_index(op.f('ix_policy_acknowledgments_organization_id'), table_name='policy_acknowledgments')
    op.drop_index(op.f('ix_policy_acknowledgments_onboarding_id'), table_name='policy_acknowledgments')
    op.drop_table('policy_acknowledgments')
    op.drop_index(op.f('ix_photo_face_tags_photo_id'), table_name='photo_face_tags')
    op.drop_index(op.f('ix_photo_face_tags_organization_id'), table_name='photo_face_tags')
    op.drop_index(op.f('ix_photo_face_tags_camper_id'), table_name='photo_face_tags')
    op.drop_table('photo_face_tags')
    op.drop_index(op.f('ix_staff_onboardings_user_id'), table_name='staff_onboardings')
    op.drop_index(op.f('ix_staff_onboardings_organization_id'), table_name='staff_onboardings')
    op.drop_table('staff_onboardings')
    # ### end Alembic commands ###
